language: scala
scala:
   - 2.12.4
script:
  - sbt ++2.11 -jvm-opts travis/jvmopts test cucumber
  - sbt ++2.12 -jvm-opts travis/jvmopts clean test
jdk:
    - oraclejdk8
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.coursier
