language: scala
scala:
   - 2.11.11
script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts test cucumber
jdk:
    - oraclejdk8
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.coursier
