language: scala
scala:
   - 2.12.4
   - 2.11.8
script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts clean test
jdk:
    - oraclejdk8
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.coursier
