//https://github.com/sbt/sbt-assembly
addSbtPlugin("com.waioeka.sbt"  % "cucumber-plugin"      % "0.1.2")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"         % "0.14.5")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"        % "0.7.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "1.5.0")
addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.28")
addSbtPlugin("com.typesafe.sbt" % "sbt-ghpages" % "0.6.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"              % "0.9.2")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"              % "1.0.0")
addSbtPlugin("com.lucidchart"   % "sbt-scalafmt"         % "1.3")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"        % "1.5.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-site"             % "1.3.1")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"         % "1.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"          % "0.3.1")
addSbtPlugin("com.eed3si9n" % "sbt-unidoc" % "0.4.1")